config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: [:new, :create, :show]
  get 'flights/index'
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, foreign_key: 'departure_id', class_name: 'Flight'
    has_many :arriving_flights, foreign_key: 'arrival_id', class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    has_many :passengers, inverse_of: :booking
    accepts_nested_attributes_for :passengers
    belongs_to :flight, class_name: 'Flight'
end

app/models/flight.rb
class Flight < ApplicationRecord
    has_many :bookings, foreign_key: :flight_id, class_name: 'Booking'
    has_many :passengers, through: :bookings
    belongs_to :departure, class_name: 'Airport'
    belongs_to :arrival, class_name: 'Airport'
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @chosen_flight_params = params
    @booking = Booking.new
    pass_num = @chosen_flight_params[:passenger_number].to_i
    pass_num.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      flash[:notice] = "You have successfully book the flight. Booking confirmation has sent to the passengers."
      redirect_to booking_path(@booking)

      # Sends emails to the passengers.
      @booking.passengers.each do |passenger|
        PassengerMailer.booked_email(passenger).deliver_now!
      end

    else
      flash[:error] = "Try again!"
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @departure_airports = Airport.select(:id, :name, :location).map { |a| ["#{a.name} #{a.location}", a.id] }
    @arrival_airports = Airport.select(:id, :name, :location).map { |a| ["#{a.name} #{a.location}", a.id] }
    @flight_dates = Flight.select(:flight_date).distinct.map { |f| [f.flight_date.strftime("%d/%m/%Y"), f.flight_date] }
    @found = Flight.where(arrival_id: params[:arrival_id], departure_id: params[:departure_id], flight_date: "#{params["flight_date(3i)"]}/#{params["flight_date(2i)"]}/#{params["flight_date(1i)"]}")
    @passenger_num = params[:passenger_num]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class='columns is-mobile is-centered'>
  <div class= 'column is-narrow'>
    <h1 class="title is-3 has-text-centered">Your Booking</h1>
    <h1 class='subtitle is-5 has-text-centered'>Enter passenger informations.</h1>
  </div>
</div></br>

<% pass_num = @chosen_flight_params[:passenger_number].to_i %>
<% flight_id = @chosen_flight_params[:id] %>
<% chosen = Flight.find(flight_id) %>

<% @booking %>
<%= form_with model: @booking do |form| %>
  <div class='columns is-mobile is-centered'>
    <div class= 'column is-narrow'>
      <h1 class='title is-5'>Date:</h1>
      <%= chosen.flight_date.strftime("%d/%m/%Y")%>
    </div>
    <div class= 'column is-narrow'>
      <h1 class='title is-5'>Departure Time:</h1>
      <%= chosen.flight_time.strftime("%k:%M")%>
    </div>
    <div class= 'column is-narrow'>
      <h1 class='title is-5'>Flight Duration:</h1>
      <%= chosen.duration %> hours
    </div>
    <div class= 'column is-narrow'>
      <h1 class='title is-5'>Departure:</h1>
      <%= chosen.departure.name %> |
      <%= chosen.departure.location %>
    </div>
    <div class= 'column is-narrow'>
      <h1 class='title is-5'>Arrival:</h1>
      <%= chosen.arrival.name %> |
      <%= chosen.arrival.location %>
    </div>
  </div></br>

    <%= form.fields_for :passengers do |sub_form| %>
        <div class='columns is-mobile is-centered'>
        <%= sub_form.text_field :name, placeholder: 'Passenger Name', class:'control' %>
        <%= sub_form.email_field :email, placeholder: 'Passenger Email', class:'control' %>
      </div></br>
    <% end %>
    <div class='columns is-mobile is-centered'>
    <%= form.hidden_field :flight_id, value: flight_id %>
    <%= form.submit %>
    </div>
<% end %>

app/views/bookings/show.html.erb
<% flight = @booking.flight %>
<% passengers = @booking.passengers %> <br>
<div class='columns is-mobile is-centered'>
<div class= 'column is-narrow'>
    <h1 class='title is-5'>Date:</h1>
    <%= flight.flight_date.strftime("%d/%m/%Y")%>
</div>
<div class= 'column is-narrow'>
    <h1 class='title is-5'>Departure Time:</h1>
    <%= flight.flight_time.strftime("%k:%M")%>
</div>
<div class= 'column is-narrow'>
    <h1 class='title is-5'>Flight Duration:</h1>
    <%= flight.duration %> hours
</div>
<div class= 'column is-narrow'>
    <h1 class='title is-5'>Departure:</h1>
    <%= flight.departure.name %> |
    <%= flight.departure.location %>
</div>
<div class= 'column is-narrow'>
    <h1 class='title is-5'>Arrival:</h1>
    <%= flight.arrival.name %> |
    <%= flight.arrival.location %>
</div>
</div></br>

<div class='columns is-mobile is-centered'>
    <% passengers.each do |p| %></br>
        <%= p.name %>
        <%= p.email %>
    <% end %>
</div></br></br>

<div class='columns is-mobile is-centered'>
    <%= link_to 'Book more flights', flights_index_path %>
</div>

app/views/flights/index.html.erb
<div class='columns is-mobile is-centered'>
  <div class= 'column is-narrow'>
    <h1 class="title is-3 has-text-centered">Flight Booker</h1>
    <h1 class='subtitle is-5 has-text-centered'>Easiest way to select your flight.</h1>
  </div>
</div></br>

<div class='columns is-mobile is-centered'>
	<%= form_with url: flights_index_path, class:'control', method: :get do |form| %>
	<%= form.label :departure, "From:" %>
	<%= form.select(:departure_id, @departure_airports, {}, { :class => '' }) %>
	<%= form.label :arrival, "To:" %>
	<%= form.select(:arrival_id, @arrival_airports, {}, { :class => '' }) %></br></br>
	<%= form.label :passenger_number, "Passengers:" %>
	<%= form.select(:passenger_num, (1..4)) %>
	<%= form.label :flight_date, "Date:" %>
	<%= form.date_select :flight_date, :order => [:day, :month, :year] %></br></br>
	<%= form.submit "Search Flight" %>
	<% end %>
</div></br>

<div class='columns is-mobile is-centered'>
	<% if !@found.empty? && !@passenger_num.nil? %>
		<%= form_with url: new_booking_path, method: :get do |form| %>
			<% @found.each do |f| %>
				<%= form.radio_button :id, f.id %>
				<%= f.id %> |
				<%= f.departure.name %>
				<%= f.departure.location %> |
				<%= f.arrival.name %>
				<%= f.arrival.location %> |
				<%= f.flight_date.strftime("%d/%m/%Y") %> |
				<%= f.flight_time.strftime("%k:%M") %>
				</br>
			<% end %>
		<%= form.hidden_field :passenger_number, value: @passenger_num %></br>
		<%= form.submit "Select Flight" %>
		<% end %>
	<% elsif @found.empty? && !@passenger_num.nil? %>
		<% flash.now[:alert] = 'No flights found.' %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% flash.each do |name, msg| -%>
      <% if name == 'error' %>
        <%= content_tag :div, msg, class: 'notification is-danger' %>
        <% elsif name == 'notice' %>
          <%= content_tag :div, msg, class: 'notification is-success' %>
        <% elsif name == 'alert' %>
          <%= content_tag :div, msg, class: 'notification is-warning' %>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>